[build]
command = "pnpm install && pnpm build"
functions = "dist"
publish = "dist"

[functions]
node_bundler = "esbuild"
included_files = ["dist/**/*", "src/**/*"]

[[redirects]]
from = "/*"
to = "/.netlify/functions/index/:splat"
status = 200
